apiVersion: v1
kind: Service
metadata:
  name: loki-server-ext
spec:
  type: NodePort
  ports:
    - port: 30049  #cluster port
      targetPort: 3100 #container port i.e for loki  it is 3100
      nodePort: 3100 #
      name: http
  selector:
    app: loki
    release: loki

