apiVersion: v1
kind: Service
metadata:
  name: otel-col-server-ext
spec:
  type: NodePort
  ports:
    - port: 30069  #cluster port
      targetPort: 4318 #container port i.e for otel-col-http it is 4318
      nodePort: 30070 #
      name: http
  selector:
    app.kubernetes.io/instance: my-opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: statefulset-collector

