apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-opentelemetry-collector
    meta.helm.sh/release-namespace: open-telemetry
  creationTimestamp: "2024-06-03T18:20:37Z"
  labels:
    app.kubernetes.io/instance: my-opentelemetry-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.101.0
    component: statefulset-collector
    helm.sh/chart: opentelemetry-collector-0.92.0
  name: my-opentelemetry-collector
  namespace: open-telemetry
  resourceVersion: "77205"
  #uid: dba548b8-de24-4d21-bb3b-d01049f40ab5
spec:
  clusterIP: 10.103.191.240
  clusterIPs:
  - 10.103.191.240
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: jaeger-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: jaeger-thrift
    port: 14268
    protocol: TCP
    targetPort: 14268
  - appProtocol: grpc
    name: otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app.kubernetes.io/instance: my-opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: statefulset-collector
  sessionAffinity: None
  type: ClusterIP
