apiVersion: v1
kind: Service
metadata:
  name: jaeger-server-ext
spec:
  type: NodePort
  ports:
    - port: 30079  #cluster port
      targetPort: 14268 #container port i.e for jaeger it is 14268
      nodePort: 30080 #
      name: http
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger

