apiVersion: v1
kind: Service
metadata:
  name: tempo-server-ext
spec:
  type: NodePort
  ports:
    - port: 30059  #cluster port
      targetPort: 3100 #container port i.e for tempo it is 3100
      nodePort: 30060 #
      name: http
  selector:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo

